### ISSUE TITLE
[Feature Request] Silent install switch

### ISSUE THREAD

**Issue by o-l-a-v** [idrassi/HashCheck#9]
Add silent install switch, so we have the ability to push this useful software from Intune, SCCM and similar.

**Comment by idrassi** [comment]
Installer can already be silent by passing `/S` switch: `HashCheckSetup-v2.5.0.1.exe /S`

Installer is made with NSIS and this is the default way to have silent installers: https://documentation.help/NSIS/Section4.12.html
